const mongoose = require("mongoose");

// Teacher Details
const teacherSchema = new mongoose.Schema({
  username: { type: String, required: true },
  name: { type: String, required: true },
  email: { type: String, required: true },
  qualification: { type: String, required: true },
  department: { type: String, required: true },
  password: { type: String, required: true },
  role: { type: String, default: " " },
  dateOfBirth: { type: Date, default: null },
  employeeId: { type: String, default: " " },
  panNumber: { type: String, default: " " },
  aadharNumber: { type: String, default: " " },
  mobileNumber: { type: String, default: " " },
  whatsappNumber: { type: String, default: " " },
  dateOfJoining: { type: Date, default: null },
  dateOfRegularAppointment: { type: Date, default: null },
  dateOfAP1Appointment: { type: Date, default: null },
  dateOfAP2Appointment: { type: Date, default: null },
  dateOfAP3Appointment: { type: Date, default: null },
  dateOfAssociateProfessorAppointment: { type: Date, default: null },
  dateOfProfessorAppointment: { type: Date, default: null },
  numberOfPhDsGuided: { type: Number, default: 0 },
  numberOfPhDsOngoing: { type: Number, default: 0 },
  numberOfMEMTechGuided: { type: Number, default: 0 },
  numberOfMEMTechOngoing: { type: Number, default: 0 },
  numberOfBEBTechProjectsGuided: { type: Number, default: 0 },
  numberOfBEBTechProjectsOngoing: { type: Number, default: 0 },
  hIndex: { type: Number, default: 0 },
  i10Index: { type: Number, default: 0 },
  totalCitationsGoogleScholar: { type: Number, default: 0 },
  totalCitationsWebOfScience: { type: Number, default: 0 },
  totalJournalPublications: { type: Number, default: 0 },
  totalConferencePublications: { type: Number, default: 0 },
  totalBookChapters: { type: Number, default: 0 },
  totalBookPublications: { type: Number, default: 0 },
  totalPatentPublications: { type: Number, default: 0 },
  orcidId: { type: String, default: " " },
  tietWebsiteLink: { type: String, default: " " },
  googleScholarLink: { type: String, default: " " },
  dblpLink: { type: String, default: " " },
  vidwaanLink: { type: String, default: " " },
  totalExternalProjects: { type: Number, default: 0 },
  amountExternalProjects: { type: Number, default: 0 },
  totalInternalProjects: { type: Number, default: 0 },
  amountInternalProjects: { type: Number, default: 0 },
  totalConsultanciesProvided: { type: Number, default: 0 },
  amountConsultancyProjects: { type: Number, default: 0 },
  collaborations: { type: String, default: " " },
  collaborators: { type: String, default: " " },
  numberOfProjectsSubmitted: { type: Number, default: 0 },
  journalReviewer: { type: String, default: " " }, // List of Journals Reviewed
});

module.exports = mongoose.model("Teacher", teacherSchema);
